import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ArrayDataService {

  constructor() { }

  data: any = [];

   arrayOfData() {
     return this.data = [
       {"cityName": "Runcorn", "countryName": "Turkmenistan", "name": "Dora", "email": "a.malesuada@Nuncullamcorpervelit.net"},
       {"cityName": "Jonqui�re", "countryName": "Greece", "name": "Barclay", "email": "Cras@tempus.org"},
       {"cityName": "St. Catharines", "countryName": "Tunisia", "name": "Talon", "email": "dolor.tempus.non@arcuNunc.net"},
       {"cityName": "Beerst", "countryName": "Comoros", "name": "Daquan", "email": "Curabitur@laoreetposuereenim.net"},
       {"cityName": "Promo-Control", "countryName": "United Arab Emirates", "name": "Holmes", "email": "feugiat.Lorem.ipsum@egestas.edu"},
       {"cityName": "Huaraz", "countryName": "Cameroon", "name": "Amal", "email": "adipiscing.fringilla@facilisis.com"},
       {"cityName": "Capestrano", "countryName": "Slovakia", "name": "Wylie", "email": "porttitor.tellus.non@milaciniamattis.net"},
       {"cityName": "Wha Ti", "countryName": "Faroe Islands", "name": "Vladimir", "email": "sollicitudin.a.malesuada@Aeneanegetmagna.net"},
       {"cityName": "Muiden", "countryName": "Djibouti", "name": "Gail", "email": "auctor.ullamcorper@sed.co.uk"},
       {"cityName": "Görlitz", "countryName": "Lesotho", "name": "Deanna", "email": "Sed@Proin.org"},
       {"cityName": "D�gelis", "countryName": "Sweden", "name": "Lysandra", "email": "Curabitur@vitae.edu"},
      {"cityName": "Juárez", "countryName": "Russian Federation", "name": "Angelica", "email": "sit.amet@tristiquesenectuset.ca"},
      {"cityName": "Jodoigne", "countryName": "Bonaire, Sint Eustatius and Saba", "name": "Hector", "email": "Integer@eget.ca"},
      {"cityName": "Nanton", "countryName": "Cyprus", "name": "Britanni", "email": "dolor@luctusaliquetodio.org"},
      {"cityName": "Serrata", "countryName": "Faroe Islands", "name": "Lael", "email": "massa.Integer.vitae@Phasellusfermentumconvallis.edu"},
      {"cityName": "Buckingham", "countryName": "Zimbabwe", "name": "Imani", "email": "rutrum.lorem.ac@lorem.com"},
      {"cityName": "Haren", "countryName": "Sudan", "name": "Colton", "email": "lorem.sit@consequat.com"},
      {"cityName": "Słupsk", "countryName": "Armenia", "name": "Lucy", "email": "auctor@Integerin.co.uk"},
      {"cityName": "Turbo", "countryName": "Guadeloupe", "name": "Tamara", "email": "eleifend.Cras@congue.ca"},
      {"cityName": "Huntsville", "countryName": "Korea, South", "name": "Eve", "email": "viverra@Aliquamrutrumlorem.com"},
      {"cityName": "Placanica", "countryName": "Australia", "name": "Clark", "email": "egestas.rhoncus.Proin@ipsumporta.edu"},
      {"cityName": "Campotosto", "countryName": "Andorra", "name": "Macey", "email": "arcu.eu.odio@imperdietdictummagna.edu"},
      {"cityName": "Montluçon", "countryName": "New Zealand", "name": "Lance", "email": "vitae.velit.egestas@aliquetnec.ca"},
      {"cityName": "Marsciano", "countryName": "Christmas Island", "name": "Allen", "email": "at.risus.Nunc@commodoipsum.ca"},
      {"cityName": "Austin", "countryName": "Monaco", "name": "Kylan", "email": "sodales.nisi@Aliquamtincidunt.edu"},
      {"cityName": "Hollange", "countryName": "New Zealand", "name": "Lester", "email": "mauris.blandit.mattis@elitCurabitur.net"},
      {"cityName": "Bolzano/Bozen", "countryName": "Taiwan", "name": "Peter", "email": "Donec.non@nunc.ca"},
      {"cityName": "Valbrevenna", "countryName": "Gabon", "name": "Hayfa", "email": "et.rutrum@id.ca"},
      {"cityName": "Chépica", "countryName": "Slovakia", "name": "Pascale", "email": "erat.semper.rutrum@pede.ca"},
      {"cityName": "Feilding", "countryName": "Macedonia", "name": "Aurelia", "email": "dictum.Phasellus.in@netus.net"},
      {"cityName": "Ourense", "countryName": "Angola", "name": "Skyler", "email": "magna.sed@magna.co.uk"},
      {"cityName": "Williams Lake", "countryName": "Russian Federation", "name": "Medge", "email": "adipiscing.fringilla@fringillacursuspurus.edu"},
      {"cityName": "Hassan", "countryName": "Djibouti", "name": "Kirestin", "email": "lectus@velvulputate.net"},
      {"cityName": "Saltara", "countryName": "Timor-Leste", "name": "Hamilton", "email": "tincidunt.vehicula@venenatis.edu"},
      {"cityName": "Lanark", "countryName": "Hong Kong", "name": "Maryam", "email": "Nullam@mipedenonummy.ca"},
      {"cityName": "Monte San Savino", "countryName": "Ukraine", "name": "Branden", "email": "sed@auctor.co.uk"},
      {"cityName": "Tijuana", "countryName": "Sweden", "name": "Rashad", "email": "ipsum.Donec.sollicitudin@magnaPraesentinterdum.co.uk"},
      {"cityName": "Anand", "countryName": "Trinidad and Tobago", "name": "Brooke", "email": "Sed.auctor.odio@sitametlorem.net"},
      {"cityName": "Chepén", "countryName": "Japan", "name": "Philip", "email": "lorem.tristique@acrisusMorbi.org"},
      {"cityName": "Coaldale", "countryName": "Benin", "name": "Phyllis", "email": "laoreet.posuere@Maurisblanditenim.edu"},
      {"cityName": "Barrie", "countryName": "Turkey", "name": "Miriam", "email": "odio.semper.cursus@ultriciesadipiscing.org"},
      {"cityName": "El Tabo", "countryName": "Christmas Island", "name": "Steven", "email": "et.netus@Aliquam.com"},
      {"cityName": "Zipaquirá", "countryName": "Vanuatu", "name": "Rhona", "email": "magnis.dis.parturient@sem.com"},
      {"cityName": "Rijkevorsel", "countryName": "Congo, the Democratic Republic of the", "name": "Elijah", "email": "sapien.gravida.non@pedesagittis.edu"},
      {"cityName": "Cholchol", "countryName": "Austria", "name": "Lacey", "email": "imperdiet.erat.nonummy@velit.co.uk"},
      {"cityName": "Raurkela Civil Township", "countryName": "Saint Lucia", "name": "Emery", "email": "bibendum@Donec.net"},
      {"cityName": "Dollard-des-Ormeaux", "countryName": "United Kingdom (Great Britain)", "name": "Marshall", "email": "arcu.Sed@facilisismagnatellus.ca"},
      {"cityName": "Quinta de Tilcoco", "countryName": "San Marino", "name": "Althea", "email": "Duis.sit@ut.co.uk"},
      {"cityName": "Sarre", "countryName": "United States", "name": "Diana", "email": "mauris.id.sapien@Pellentesque.org"},
      {"cityName": "Grimaldi", "countryName": "Ukraine", "name": "Jameson", "email": "velit.Quisque@Duiscursus.ca"},
      {"cityName": "Beerse", "countryName": "French Southern Territories", "name": "Kyra", "email": "id.libero@tempor.co.uk"},
      {"cityName": "Nashik", "countryName": "Mozambique", "name": "Maggie", "email": "vitae.erat@elementumategestas.net"},
      {"cityName": "Lloydminster", "countryName": "Israel", "name": "Regina", "email": "sit@senectusetnetus.edu"},
      {"cityName": "Vitória da Conquista", "countryName": "Barbados", "name": "Willow", "email": "rutrum.eu.ultrices@atlibero.net"},
      {"cityName": "Clarksville", "countryName": "Mongolia", "name": "Giacomo", "email": "est.tempor.bibendum@Fuscemollis.edu"},
      {"cityName": "Antakya", "countryName": "Sudan", "name": "Tyler", "email": "neque.Morbi@rutrum.org"},
      {"cityName": "Lachine", "countryName": "Tanzania", "name": "Anastasia", "email": "ridiculus.mus@Pellentesqueultriciesdignissim.co.uk"},
      {"cityName": "Thames", "countryName": "Rwanda", "name": "Martha", "email": "neque.Morbi.quis@risus.edu"},
      {"cityName": "Barnstaple", "countryName": "Martinique", "name": "Gretchen", "email": "faucibus@Donecestmauris.net"},
      {"cityName": "Macerata", "countryName": "Cuba", "name": "Buckminster", "email": "id@Inornare.org"},
      {"cityName": "Saint-Dié-des-Vosges", "countryName": "Dominica", "name": "Denton", "email": "Curabitur.ut@Cras.co.uk"},
      {"cityName": "Landshut", "countryName": "Saint Pierre and Miquelon", "name": "Shoshana", "email": "interdum.Nunc.sollicitudin@vitae.co.uk"},
      {"cityName": "Topeka", "countryName": "Moldova", "name": "Rogan", "email": "fringilla.ornare@Vivamus.co.uk"},
      {"cityName": "Goslar", "countryName": "Grenada", "name": "Celeste", "email": "aliquet.lobortis@dui.co.uk"},
      {"cityName": "Saravena", "countryName": "Ireland", "name": "Trevor", "email": "lacinia.mattis.Integer@Vivamusmolestiedapibus.org"},
      {"cityName": "New Haven", "countryName": "Sweden", "name": "Caldwell", "email": "venenatis@eget.net"},
      {"cityName": "Tiruvarur", "countryName": "Albania", "name": "Avram", "email": "Nunc.mauris@Curabiturdictum.net"},
      {"cityName": "Ensenada", "countryName": "Viet Nam", "name": "Olga", "email": "a.dui.Cras@justoProinnon.com"},
      {"cityName": "Vico del Gargano", "countryName": "Lesotho", "name": "Maris", "email": "laoreet@utdolor.edu"},
      {"cityName": "Vöcklabruck", "countryName": "Viet Nam", "name": "Oliver", "email": "elit.a@felispurusac.org"},
      {"cityName": "San Mauro Marchesato", "countryName": "United Arab Emirates", "name": "Colorado", "email": "Phasellus.elit.pede@tellusAenean.co.uk"},
      {"cityName": "Markham", "countryName": "Antarctica", "name": "Fredericka", "email": "Mauris@maurisaliquam.ca"},
      {"cityName": "Geesthacht", "countryName": "Saint Helena, Ascension and Tristan da Cunha", "name": "Rhoda", "email": "in@etmagnisdis.org"},
      {"cityName": "Recife", "countryName": "Guadeloupe", "name": "Catherine", "email": "In.lorem@liberoatauctor.co.uk"},
      {"cityName": "Saint-Pierre", "countryName": "South Georgia and The South Sandwich Islands", "name": "Bernard", "email": "odio.sagittis.semper@NullafacilisiSed.org"},
      {"cityName": "Vitry-sur-Seine", "countryName": "Bouvet Island", "name": "Dane", "email": "tristique@etrutrumnon.com"},
      {"cityName": "Luckenwalde", "countryName": "Morocco", "name": "Kessie", "email": "diam@Donecsollicitudin.org"},
      {"cityName": "Lampernisse", "countryName": "Jamaica", "name": "Laith", "email": "Nullam.suscipit.est@aptenttaciti.org"},
      {"cityName": "Saint-Sébastien-sur-Loire", "countryName": "Cameroon", "name": "Arden", "email": "senectus.et.netus@lacus.com"},
      {"cityName": "Elmshorn", "countryName": "Slovenia", "name": "Amethyst", "email": "at@nonlobortisquis.edu"},
      {"cityName": "Provost", "countryName": "Serbia", "name": "Amal", "email": "Nulla.semper.tellus@ametrisusDonec.ca"},
      {"cityName": "Hulste", "countryName": "British Indian Ocean Territory", "name": "Victor", "email": "laoreet.libero.et@infelis.org"},
      {"cityName": "Manisa", "countryName": "Holy See (Vatican City State)", "name": "Dean", "email": "lacus.Nulla.tincidunt@felisorci.co.uk"},
      {"cityName": "Baltasound", "countryName": "Holy See (Vatican City State)", "name": "Mark", "email": "viverra@turpisAliquamadipiscing.edu"},
      {"cityName": "Pyeongtaek", "countryName": "Antarctica", "name": "Cheryl", "email": "Proin.velit.Sed@euismodetcommodo.ca"},
      {"cityName": "Chelsea", "countryName": "Czech Republic", "name": "Maris", "email": "pellentesque.massa.lobortis@ante.net"},
      {"cityName": "Sasaram", "countryName": "Colombia", "name": "Mark", "email": "nisl.Nulla@semconsequatnec.edu"},
      {"cityName": "Vertou", "countryName": "Libya", "name": "Cameron", "email": "tristique.ac@estconguea.edu"},
      {"cityName": "Baddeck", "countryName": "Montenegro", "name": "Thor", "email": "Quisque.ac@Donec.net"},
      {"cityName": "Bolzano Vicentino", "countryName": "Sri Lanka", "name": "Jordan", "email": "felis.Nulla@leoinlobortis.org"},
      {"cityName": "Houtvenne", "countryName": "Haiti", "name": "Ava", "email": "tempus.non@quamCurabitur.org"},
      {"cityName": "San José de Maipo", "countryName": "Netherlands", "name": "Jack", "email": "eleifend@velpedeblandit.ca"},
      {"cityName": "Rocca San Felice", "countryName": "Antigua and Barbuda", "name": "Kelly", "email": "a.magna@adui.co.uk"},
      {"cityName": "Caucaia", "countryName": "Åland Islands", "name": "Lareina", "email": "quis@ornareegestas.com"},
      {"cityName": "San Pedro", "countryName": "Angola", "name": "Joel", "email": "tincidunt@euismodindolor.net"},
      {"cityName": "Zvenigorod", "countryName": "Kuwait", "name": "Valentine", "email": "ullamcorper.magna.Sed@tincidunttempus.net"},
      {"cityName": "Mühlheim am Main", "countryName": "Puerto Rico", "name": "Serina", "email": "magna.Praesent.interdum@mollisDuis.net"},
      {"cityName": "Kasli", "countryName": "Zimbabwe", "name": "Quemby", "email": "dui.in.sodales@ligula.net"},
      {"cityName": "Lodine", "countryName": "Greece", "name": "Quynn", "email": "mauris.aliquam@metus.org"},
      {"cityName": "Copertino", "countryName": "Paraguay", "name": "Forrest", "email": "arcu.Curabitur.ut@sollicitudincommodoipsum.com"}
    ];
   }
  
   
  
}
